### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Chist-Sergey** [Chist-Sergey/Makefile-Generator#1]
For some reason I get this error when I try to run any script.  
The cause is unknown.  
This error occurred when I was installing Python via Brew with `brew install python`.
Full error:
```
Traceback (most recent call last):
  File "genmakefile-v1.0.py", line 8, in <module>
    def generate_makefile(apps: dict[str, str]) -> None:
TypeError: 'type' object is not subscriptable
```
A similar error occurred when I tried to run this script with Python 2:
```
  File "genmakefile-v1.0.py", line 9
    def generate_makefile(apps: dict[str, str]) -> None:
                              ^
SyntaxError: invalid syntax
```
Removing type annotation should resolve this issue.

**Comment by Chist-Sergey** [comment]
Current status: Trying to replicate.
